name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo ${GITHUB_REF#refs/heads/}
      - name: Git Checkout Latest
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.REGISTRY_URL }}/aldebaranode-docs
          tags: |
            type=sha
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.REGISTRY_URL }}/aldebaranode-docs:main
            docker container stop aldebaranode-docs
            docker container rm -f aldebaranode-docs || true
            docker run -d --name aldebaranode-docs --restart always -p 5003:3000 ${{ secrets.REGISTRY_URL }}/aldebaranode-docs:main
            docker rmi $(docker images ${{ secrets.REGISTRY_URL }}/aldebaranode-docs -f "dangling=true" -q) || true